# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI & CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID:      ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID:  ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN:       ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --confirm
